/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author syase
 */

import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.JOptionPane;

public class add extends javax.swing.JFrame {

    /**
     * Creates new form add
     */
    String db_URL ="jdbc:mysql://localhost:3306/sports_mania?zeroDateTimeBehavior=convertToNull";
    String db_USER="root";
    String db_password="";
    Connection conn=null;
    Statement stmt=null;
    ResultSet rs=null;
    DefaultComboBoxModel track_mdl=new DefaultComboBoxModel();
    DefaultComboBoxModel field_mdl=new DefaultComboBoxModel();
    DefaultComboBoxModel games_mdl=new DefaultComboBoxModel();
    DefaultComboBoxModel emp_mdl=new DefaultComboBoxModel();
    String colour="",tm="";
    int uni;
    private int count;
    private int i;
   
   
    
   public add() throws SQLException {
        initComponents();
        emp_mdl.addElement("EMPTY");
        
        track_mdl.addElement("1200 M");
        track_mdl.addElement("200 M");
        track_mdl.addElement("100 M");
        track_mdl.addElement("4x100 MIX");
         track_mdl.addElement("RELAY");
        
       
        
      
        field_mdl.addElement("SHORT PUTS");
        
        
        games_mdl.addElement("FUTSAL");
        games_mdl.addElement("DODGE BALL");
        games_mdl.addElement("TUG OF WAR");
        games_mdl.addElement("OBSTACLE RACE");
        games_mdl.addElement("AEROBICS");
        games_mdl.addElement("MARCH-PAST");
     
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gender = new javax.swing.ButtonGroup();
        dept = new javax.swing.ButtonGroup();
        yr = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        name_tf = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        age_tf = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        male_rb = new javax.swing.JRadioButton();
        female_rb = new javax.swing.JRadioButton();
        o_rb = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        email_tf = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        phone_tf = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        com_sub_event = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        bamc_rb = new javax.swing.JRadioButton();
        bsw_rb = new javax.swing.JRadioButton();
        bca_rb = new javax.swing.JRadioButton();
        bbatt_rb = new javax.swing.JRadioButton();
        bbmm_rb = new javax.swing.JRadioButton();
        submit = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        rollno_tf = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        com_event_name = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        fy_rb = new javax.swing.JRadioButton();
        sy_rb = new javax.swing.JRadioButton();
        ty_rb = new javax.swing.JRadioButton();
        bba_rb = new javax.swing.JRadioButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 0, 0));

        jLabel1.setBackground(new java.awt.Color(255, 51, 0));
        jLabel1.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        jLabel1.setText("SPORTS MANIA 2019-2020");

        jLabel2.setBackground(new java.awt.Color(153, 153, 153));
        jLabel2.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel2.setText("NAME");

        name_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name_tfActionPerformed(evt);
            }
        });
        name_tf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                name_tfKeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel3.setText("AGE(18+)");

        age_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                age_tfActionPerformed(evt);
            }
        });
        age_tf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                age_tfKeyTyped(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel4.setText("GENDER");

        gender.add(male_rb);
        male_rb.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        male_rb.setText("MALE");

        gender.add(female_rb);
        female_rb.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        female_rb.setText("FEMALE");

        gender.add(o_rb);
        o_rb.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        o_rb.setText("LGBTQ");

        jLabel5.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel5.setText("EMAIL");

        email_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                email_tfActionPerformed(evt);
            }
        });
        email_tf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                email_tfKeyTyped(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel6.setText("MOBILE  NO:");

        phone_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phone_tfActionPerformed(evt);
            }
        });
        phone_tf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                phone_tfKeyTyped(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel7.setText("CHOOSE   THE    EVENT   YOU   WANT   TO   PARTICIPATE");

        com_sub_event.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        com_sub_event.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None" }));
        com_sub_event.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                com_sub_eventActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel8.setText("DEPARTMENT");

        dept.add(bamc_rb);
        bamc_rb.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        bamc_rb.setText("BAMC");
        bamc_rb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bamc_rbActionPerformed(evt);
            }
        });

        dept.add(bsw_rb);
        bsw_rb.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        bsw_rb.setText("BSW");

        dept.add(bca_rb);
        bca_rb.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        bca_rb.setText("BCA");

        dept.add(bbatt_rb);
        bbatt_rb.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        bbatt_rb.setText("BBA T&T");

        dept.add(bbmm_rb);
        bbmm_rb.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        bbmm_rb.setText("BBMM");

        submit.setBackground(new java.awt.Color(255, 255, 255));
        submit.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        submit.setText("SUBMIT");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel9.setText("ROLL NO");

        rollno_tf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                rollno_tfKeyTyped(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Bahnschrift", 0, 36)); // NOI18N
        jLabel10.setText("DON BOSCO COLLEGE");

        com_event_name.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        com_event_name.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Event", "Track Event", "Field Event", "Games" }));
        com_event_name.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                com_event_nameMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                com_event_nameMouseReleased(evt);
            }
        });
        com_event_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                com_event_nameActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel11.setText("YEAR");

        yr.add(fy_rb);
        fy_rb.setText("FY");

        yr.add(sy_rb);
        sy_rb.setText("SY");

        yr.add(ty_rb);
        ty_rb.setText("TY");

        dept.add(bba_rb);
        bba_rb.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        bba_rb.setText("BBA");

        jLabel13.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel13.setText("SHOW PARTICIPANTS FOR EACH EVENT");

        jLabel14.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel14.setText("SELECT TEAM");

        jButton4.setBackground(new java.awt.Color(255, 255, 0));
        jButton4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton4.setText("EXIT");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(255, 204, 0));
        jButton5.setText("EVENTS");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(167, 167, 167))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(272, 272, 272))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(phone_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(512, 512, 512))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(fy_rb, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(sy_rb, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(ty_rb, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 128, Short.MAX_VALUE)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(email_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(146, 146, 146))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(22, 22, 22)
                                        .addComponent(bamc_rb, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(28, 28, 28)
                                        .addComponent(bsw_rb, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(30, 30, 30)
                                        .addComponent(bca_rb, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(29, 29, 29)
                                .addComponent(bbatt_rb, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(bbmm_rb, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(26, 26, 26)
                                    .addComponent(bba_rb, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(male_rb, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(61, 61, 61)
                                            .addComponent(female_rb, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(61, 61, 61)
                                            .addComponent(o_rb, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(name_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(126, 126, 126)
                                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(rollno_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(age_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(2, 2, 2))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(com_event_name, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(com_sub_event, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(79, 79, 79)
                        .addComponent(submit, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton4)
                        .addGap(100, 100, 100))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(name_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(age_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rollno_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(male_rb, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(female_rb, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(o_rb, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bamc_rb)
                        .addComponent(bsw_rb)
                        .addComponent(bca_rb)
                        .addComponent(bbatt_rb)
                        .addComponent(bbmm_rb)
                        .addComponent(bba_rb)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fy_rb, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sy_rb, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ty_rb)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(email_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phone_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(com_event_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(com_sub_event, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(submit, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(159, 159, 159))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void com_event_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_com_event_nameActionPerformed
        // TODO add your handling code here:
      if(com_event_name.getSelectedIndex()==0)
        {
            JOptionPane.showMessageDialog(rootPane,"Select An Event");
        }
          if(com_event_name.getSelectedIndex()==1)
        {
            com_sub_event.setModel(track_mdl);
        }
        else if(com_event_name.getSelectedIndex()==2)
        {
            com_sub_event.setModel(field_mdl);
        }
        else if(com_event_name.getSelectedIndex()==3)
        {
            com_sub_event.setModel(games_mdl);
        }
    }//GEN-LAST:event_com_event_nameActionPerformed

    private void rollno_tfKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rollno_tfKeyTyped
        char ch=evt.getKeyChar();
     
        if(((ch <'0' || ch>'9') && (ch !='\b')) || rollno_tf.getText().length()==2 )
        {
            evt.consume();
           
        }
    }//GEN-LAST:event_rollno_tfKeyTyped

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        int roll=Integer.parseInt(rollno_tf.getText());
        String name=name_tf.getText();
        String mail=email_tf.getText();
        int ag=Integer.parseInt(age_tf.getText());
        //uni=Integer.parseInt(uni_tf.getText());
       // int ph=Integer.parseInt(phone_tf.getText());
        char gender=' ';
        String dep=" ",f=" ";
//gender
        if(male_rb.isSelected())
        {
            gender='M';
        }
        else if(female_rb.isSelected())
        {
            gender='F';
        }
        else if(o_rb.isSelected())
        {
            gender='O';
        }
        //dept
        if(bamc_rb.isSelected())
        {
            dep="BAMC";
        }
        else if(bsw_rb.isSelected())
        {
            dep="BSW";
        }
        else if(bca_rb.isSelected())
        {
            dep="BCA";
        }
        else if(bbatt_rb.isSelected())
        {
            dep="BBA T&T";
        }
        else if(bbmm_rb.isSelected())
        {
            dep="BBMM";
        }
        else if(bba_rb.isSelected())
        {
            dep="BBA";
        }
        //colour code
        if(fy_rb.isSelected()&&bba_rb.isSelected())
        {
            colour="Yellow";
        }
        else if(sy_rb.isSelected()&&bba_rb.isSelected())
        {
            colour="Brown";
        }
        else if(ty_rb.isSelected()&&bba_rb.isSelected())
        {
            colour="Floresent Blue";
        }
        else  if(fy_rb.isSelected()&&bamc_rb.isSelected())
        {
            colour="Light Gray";
        }
        else if(sy_rb.isSelected()&&bamc_rb.isSelected())
        {
            colour="Black";
        }
        else if(ty_rb.isSelected()&&bbmm_rb.isSelected() && ty_rb.isSelected() && bsw_rb.isSelected())
        {
            colour="Florescent Blue";
        }
        else if(fy_rb.isSelected()&&bbatt_rb.isSelected())
        {
            colour="Green";
        }
        else if(sy_rb.isSelected()&&bbatt_rb.isSelected())
        {
            colour="Red";
        }
        else if(ty_rb.isSelected()&&bbatt_rb.isSelected())
        {
            colour="Orange";
        }
        else  if(fy_rb.isSelected()&&bca_rb.isSelected())
        {
            colour="Purple";
        }
        else if(sy_rb.isSelected()&&bca_rb.isSelected())
        {
            colour="Blue";
        }
        else   if(ty_rb.isSelected()&&bca_rb.isSelected())
        {
            colour="Maroon";
        }
        //year
        if(fy_rb.isSelected())
        {
            f="FY";

        }
        else if(sy_rb.isSelected())
        {
            f="SY";
        }
        else if(ty_rb.isSelected())
        {
            f="TY";
        }
        //team
        if(fy_rb.isSelected()&&bba_rb.isSelected())
        {
            tm="FYBBA";
        }
        else if(sy_rb.isSelected()&&bba_rb.isSelected())
        {
            tm="SYBBA";
        }
        else if(ty_rb.isSelected()&&bba_rb.isSelected())
        {
            tm="TYBBA";
        }
        else  if(fy_rb.isSelected()&&bamc_rb.isSelected())
        {
            tm="FYBAMC";
        }
        else if(sy_rb.isSelected()&&bamc_rb.isSelected())
        {
            tm="SYBAMC";
        }
         else if(ty_rb.isSelected()&&bamc_rb.isSelected())
        {
            JOptionPane.showMessageDialog(rootPane,"TEAM NOT AVAILABLE...PLEASE CHOOSE OTHER TEAM");
            return ;
        }
         else if(fy_rb.isSelected()&& bbmm_rb.isSelected())
        {
          JOptionPane.showMessageDialog(rootPane,"TEAM NOT AVAILABLE...PLEASE CHOOSE OTHER TEAM");
            return ;
        }
          else if(sy_rb.isSelected()&& bbmm_rb.isSelected())
        {
           JOptionPane.showMessageDialog(rootPane,"TEAM NOT AVAILABLE...PLEASE CHOOSE OTHER TEAM");
            return ;
        }
         else if(ty_rb.isSelected()&& bbmm_rb.isSelected())
        {
            tm="TYBBMM";
        }
         else if(fy_rb.isSelected() && bsw_rb.isSelected())
        {
           JOptionPane.showMessageDialog(rootPane,"TEAM NOT AVAILABLE...PLEASE CHOOSE OTHER TEAM");
            return ;
        }
          else if(sy_rb.isSelected() && bsw_rb.isSelected())
        {
           JOptionPane.showMessageDialog(rootPane,"TEAM NOT AVAILABLE...PLEASE CHOOSE OTHER TEAM");
            return ;
        }
         else if(ty_rb.isSelected() && bsw_rb.isSelected())
        {
            tm="TYBSW";
        }
        else if(fy_rb.isSelected()&&bbatt_rb.isSelected())
        {
            tm="FYBBA T&T";
        }
        else if(sy_rb.isSelected()&&bbatt_rb.isSelected())
        {
          tm="SYBBA T&T";
        }
        else if(ty_rb.isSelected()&&bbatt_rb.isSelected())
        {
            tm="TYBBA T&T";
        }
        else  if(fy_rb.isSelected()&&bca_rb.isSelected())
        {
            tm="FYBCA";
        }
        else if(sy_rb.isSelected()&&bca_rb.isSelected())
        {
            tm="SYBCA";
        }
        else   if(ty_rb.isSelected()&&bca_rb.isSelected())
        {
            tm="TYBCA";
        }
        if(fy_rb.isSelected())
        {
            f="FY";

        }
        else if(sy_rb.isSelected())
        {
            f="SY";
        }
        else if(ty_rb.isSelected())
        {
            f="TY";
        }
        
        {
   
      {
          
          if(sy_rb.isSelected() && bca_rb.isSelected() && com_event_name.getSelectedIndex()==1 )
          {
              if(count<1)
              {
            
          }
          
          else
          {
               JOptionPane.showMessageDialog(rootPane, "participate person");
          }
          
      }
     
         
           {
                
            }
          
           
       
        String query="INSERT INTO sports_mania_table VALUES('"+roll+"','"+name+"','"+mail+"','"+ag+"','"+phone_tf.getText()+"','"+gender+"','"+f+"','"+dep+"','"+com_sub_event.getSelectedItem()+"','"+colour+"','"+uni+"','"+tm+"');";
        //JOptionPane.showMessageDialog(rootPane, query);
if((name_tf.getText().trim().equals("")))
        {
            JOptionPane.showMessageDialog(rootPane, "name is  mandatory");                                                      //'"+uni+"',
        }
        else if((age_tf.getText().trim().equals(""))|| Integer.parseInt(age_tf.getText()) <= 18)
        {
            JOptionPane.showMessageDialog(rootPane, "age is  mandatory");
        }
        else if(male_rb == null || female_rb==null || o_rb==null)
        {
            JOptionPane.showMessageDialog(rootPane, "select a gender");
        }
           else if((phone_tf.getText().trim().equals("")) && phone_tf.getText().length()==10)
        {
            JOptionPane.showMessageDialog(rootPane, "Enter a valid phone number");
        }
        else if(email_tf.getText().trim().equals(""))
        {
            JOptionPane.showMessageDialog(rootPane, "Enter a emailphone number");
        }
       /* else if(com_event_name.getSelectedIndex()==0)
        {
            JOptionPane.showMessageDialog(rootPane, "Select an event");
        }*/
        
      else
        {
            JOptionPane.showMessageDialog(rootPane, "submission successful");
        }
        int i;
        try
        {
            conn= DriverManager.getConnection(db_URL,db_USER,db_password);
            stmt=conn.createStatement();
            i=stmt.executeUpdate(query);

        }
        //catch (MySQLIntegrityConstraintViolationException ex) {

            // JOptionPane.showMessageDialog(rootPane,uni);
            // }

        catch(SQLException e)
        {
            System.out.print("SQL EXCEPTION"+e.toString());
        }
        catch(Exception ex)
        {
            System.out.print("EXCEPTION"+ex.getMessage());
        }
        }}
        
    }//GEN-LAST:event_submitActionPerformed

    private void com_sub_eventActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_com_sub_eventActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_com_sub_eventActionPerformed

    private void phone_tfKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phone_tfKeyTyped
        char ch=evt.getKeyChar();
      if(((ch < '0' || ch > '9') && (ch !='\b')) || phone_tf.getText().length()==10)
         evt.consume();
    }//GEN-LAST:event_phone_tfKeyTyped

    private void phone_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phone_tfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phone_tfActionPerformed

    private void email_tfKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_email_tfKeyTyped
        char ch=evt.getKeyChar();
        //String s="";
        if((ch < 'a' || ch> 'z') &&  (ch!=' ') &&(ch < '0' || ch > '9')&&(ch!='\b') && (ch!='@')&&(ch!='.')&&(ch!='_')&&(ch!='>')&&(ch!='<')){
            evt.consume();
        }
    }//GEN-LAST:event_email_tfKeyTyped

    private void age_tfKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_age_tfKeyTyped
        char ch=evt.getKeyChar();
        if(((ch <'0' || ch>'9') && (ch !='\b')) || age_tf.getText().length()==2)
        {
            evt.consume();
        }
    }//GEN-LAST:event_age_tfKeyTyped

    private void age_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_age_tfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_age_tfActionPerformed

    private void name_tfKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_name_tfKeyTyped
        // TODO add your handling code here:
        char ch=evt.getKeyChar();
        if((ch < 'a' || ch> 'z') && (ch<'A' || ch>'Z') && (ch!=' ') &&(ch!='\b')){
            evt.consume();
        }
    }//GEN-LAST:event_name_tfKeyTyped

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
      System.exit(0);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
   dispose();
   events_sports es=new events_sports();
   es.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void bamc_rbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bamc_rbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bamc_rbActionPerformed

    private void email_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_email_tfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_email_tfActionPerformed

    private void com_event_nameMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_com_event_nameMouseReleased
      
    }//GEN-LAST:event_com_event_nameMouseReleased

    private void com_event_nameMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_com_event_nameMouseExited
     
    }//GEN-LAST:event_com_event_nameMouseExited

    private void name_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name_tfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_name_tfActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new add().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(add.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField age_tf;
    private javax.swing.JRadioButton bamc_rb;
    private javax.swing.JRadioButton bba_rb;
    private javax.swing.JRadioButton bbatt_rb;
    private javax.swing.JRadioButton bbmm_rb;
    private javax.swing.JRadioButton bca_rb;
    private javax.swing.JRadioButton bsw_rb;
    private javax.swing.JComboBox<String> com_event_name;
    private javax.swing.JComboBox<String> com_sub_event;
    private javax.swing.ButtonGroup dept;
    private javax.swing.JTextField email_tf;
    private javax.swing.JRadioButton female_rb;
    private javax.swing.JRadioButton fy_rb;
    private javax.swing.ButtonGroup gender;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton male_rb;
    private javax.swing.JTextField name_tf;
    private javax.swing.JRadioButton o_rb;
    private javax.swing.JTextField phone_tf;
    private javax.swing.JTextField rollno_tf;
    private javax.swing.JButton submit;
    private javax.swing.JRadioButton sy_rb;
    private javax.swing.JRadioButton ty_rb;
    private javax.swing.ButtonGroup yr;
    // End of variables declaration//GEN-END:variables
}
