/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author UZUMA
 */
public class Obstacle extends javax.swing.JFrame {
String db_URL="jdbc:mysql://localhost:3306/sports_mania?zeroDateTimeBehavior=convertToNull";
    String db_USER="root";
    String db_password="";
    Connection conn=null;
    Statement stmt=null;
    ResultSet rs=null;
    public Obstacle() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        p = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        team_com = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        n_tf = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 51));

        p.setBackground(new java.awt.Color(153, 255, 204));
        p.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "roll", "name", "mail", "ag", "ph", "gender", "Year", "dep", "event", "colour", "Unique Chest Number", "Team"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(p);

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setText("INSERT");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setText("DELETE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setText("EXIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        team_com.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select team", "FYBBA", "SYBBA", "TYBBA", "FYBAMC", "SYBAMC", "TYBBMM", "TYBSW", "FYBBA T&T", "SYBBA T&T", "TYBBA T&T", "FYBCA", "SYBCA", "TYBCA" }));
        team_com.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                team_comActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        jLabel1.setText("OBSTACLE RACE");

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setText("BACK");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel2.setText("ENTER THE ROLL NUMBER  TO BE DELETED");

        jButton5.setText("REFRESH");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(n_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(90, 90, 90)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(115, 115, 115)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(306, 306, 306)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(team_com, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(team_com, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(n_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(79, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
dispose();  
        mania3 m3=new mania3();
m3.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
int y=(int)Integer.parseInt(n_tf.getText());        
      //  DefaultTableModel model = (DefaultTableModel) p.getModel();


       try{
       
      //model.removeRow(SelectedRowIndex);
        conn=DriverManager.getConnection(db_URL,db_USER,db_password);
            stmt=conn.createStatement();
            int i=stmt.executeUpdate("DELETE FROM sports_mania_table WHERE roll="+y+" ;");
     //    p.clearSelection();
            if(i>=0)
                
                javax.swing.JOptionPane.showMessageDialog(rootPane, "DELETE SUCCESSFUL");
            conn.close();
       }
       catch(SQLException e)
        {
            System.out.print("SQL EXCEPTION"+e.getMessage());
        }
        catch(Exception x)
        {
            System.out.print("EXCEPTION"+x.getMessage());
        }    
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void team_comActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_team_comActionPerformed
if(team_com.getSelectedIndex()==1)
        {
            int rows=0,cols=0;
            //int i = 0;
            //DefaultTableModel model=( DefaultTableModel) x.getModel();
            try
            {
                conn=DriverManager.getConnection(db_URL,db_USER,db_password);
                stmt=conn.createStatement();
                rs=stmt.executeQuery("SELECT * FROM sports_mania_table WHERE Team='FYBBA' AND event='OBSTACLE RACE';");

                while(rs.next())
                {
                    p.setValueAt(rs.getString(1), rows, cols++);
                    p.setValueAt(rs.getString(2), rows, cols++);
                    p.setValueAt(rs.getString(3), rows, cols++);
                    p.setValueAt(rs.getString(4), rows, cols++);
                    p.setValueAt(rs.getString(5), rows, cols++);
                    p.setValueAt(rs.getString(6), rows, cols++);
                    p.setValueAt(rs.getString(7), rows, cols++);
                    p.setValueAt(rs.getString(8), rows, cols++);
                    p.setValueAt(rs.getString(9), rows, cols++);
                    p.setValueAt(rs.getString(10), rows, cols++);
                    p.setValueAt(rs.getInt(11), rows, cols++);
                    p.setValueAt(rs.getString(12), rows, cols++);
                    rows++;
                    cols=0;

                }

                rs.close();
                stmt.close();
                conn.close();

            }

            catch(SQLException e)
            {
                System.out.print("  SQL EXCEPTION  "+e.getMessage());
            }
            catch(Exception ex)
            {
                System.out.print("  EXCEPTION  "+ex.getMessage());
            }

        }
        else if(team_com.getSelectedIndex()==2)
        {
            int rows=0,cols=0;
            //int i = 0;
            // DefaultTableModel model=( DefaultTableModel) x.getModel();
            try
            {
                conn=DriverManager.getConnection(db_URL,db_USER,db_password);
                stmt=conn.createStatement();
                rs=stmt.executeQuery("SELECT * FROM sports_mania_table WHERE Team='SYBBA' AND event='OBSTACLE RACE';");

                while(rs.next())
                {
                    p.setValueAt(rs.getString(1), rows, cols++);
                    p.setValueAt(rs.getString(2), rows, cols++);
                    p.setValueAt(rs.getString(3), rows, cols++);
                    p.setValueAt(rs.getString(4), rows, cols++);
                    p.setValueAt(rs.getString(5), rows, cols++);
                    p.setValueAt(rs.getString(6), rows, cols++);
                    p.setValueAt(rs.getString(7), rows, cols++);
                    p.setValueAt(rs.getString(8), rows, cols++);
                    p.setValueAt(rs.getString(9), rows, cols++);
                    p.setValueAt(rs.getString(10), rows, cols++);
                    p.setValueAt(rs.getInt(11), rows, cols++);
                    p.setValueAt(rs.getString(12), rows, cols++);
                    rows++;
                    cols=0;

                }

                rs.close();
                stmt.close();
                conn.close();

            }

            catch(SQLException e)
            {
                System.out.print("  SQL EXCEPTION  "+e.getMessage());
            }
            catch(Exception ex)
            {
                System.out.print("  EXCEPTION  "+ex.getMessage());
            }
        }
        else if(team_com.getSelectedIndex()==3)
        {
            int rows=0,cols=0;
            //int i = 0;
            // DefaultTableModel model=( DefaultTableModel) x.getModel();
            try
            {
                conn=DriverManager.getConnection(db_URL,db_USER,db_password);
                stmt=conn.createStatement();
                rs=stmt.executeQuery("SELECT * FROM sports_mania_table WHERE Team='TYBBA' AND event='OBSTACLE RACE';");

                while(rs.next())
                {
                    p.setValueAt(rs.getString(1), rows, cols++);
                    p.setValueAt(rs.getString(2), rows, cols++);
                    p.setValueAt(rs.getString(3), rows, cols++);
                    p.setValueAt(rs.getString(4), rows, cols++);
                    p.setValueAt(rs.getString(5), rows, cols++);
                    p.setValueAt(rs.getString(6), rows, cols++);
                    p.setValueAt(rs.getString(7), rows, cols++);
                    p.setValueAt(rs.getString(8), rows, cols++);
                    p.setValueAt(rs.getString(9), rows, cols++);
                    p.setValueAt(rs.getString(10), rows, cols++);
                    p.setValueAt(rs.getInt(11), rows, cols++);
                    p.setValueAt(rs.getString(12), rows, cols++);
                    rows++;
                    cols=0;

                }

                rs.close();
                stmt.close();
                conn.close();

            }

            catch(SQLException e)
            {
                System.out.print("  SQL EXCEPTION  "+e.getMessage());
            }
            catch(Exception ex)
            {
                System.out.print("  EXCEPTION  "+ex.getMessage());
            }
        }
        else   if(team_com.getSelectedIndex()==4)
        {
            int rows=0,cols=0;
            // int i = 0;
            //  DefaultTableModel model=( DefaultTableModel) x.getModel();
            try
            {
                conn=DriverManager.getConnection(db_URL,db_USER,db_password);
                stmt=conn.createStatement();
                rs=stmt.executeQuery("SELECT * FROM sports_mania_table WHERE Team='FYBAMC' AND event='OBSTACLE RACE';");

                while(rs.next())
                {
                    p.setValueAt(rs.getString(1), rows, cols++);
                    p.setValueAt(rs.getString(2), rows, cols++);
                    p.setValueAt(rs.getString(3), rows, cols++);
                    p.setValueAt(rs.getString(4), rows, cols++);
                    p.setValueAt(rs.getString(5), rows, cols++);
                    p.setValueAt(rs.getString(6), rows, cols++);
                    p.setValueAt(rs.getString(7), rows, cols++);
                    p.setValueAt(rs.getString(8), rows, cols++);
                    p.setValueAt(rs.getString(9), rows, cols++);
                    p.setValueAt(rs.getString(10), rows, cols++);
                    p.setValueAt(rs.getInt(11), rows, cols++);
                    p.setValueAt(rs.getString(12), rows, cols++);
                    rows++;
                    cols=0;

                }

                rs.close();
                stmt.close();
                conn.close();

            }

            catch(SQLException e)
            {
                System.out.print("  SQL EXCEPTION  "+e.getMessage());
            }
            catch(Exception ex)
            {
                System.out.print("  EXCEPTION  "+ex.getMessage());
            }
        }

        else   if(team_com.getSelectedIndex()==5)
        {
            int rows=0,cols=0;
            // int i = 0;
            //  DefaultTableModel model=( DefaultTableModel) x.getModel();
            try
            {
                conn=DriverManager.getConnection(db_URL,db_USER,db_password);
                stmt=conn.createStatement();
                rs=stmt.executeQuery("SELECT * FROM sports_mania_table WHERE Team='SYBAMC' AND event='OBSTACLE RACE';");

                while(rs.next())
                {
                    p.setValueAt(rs.getString(1), rows, cols++);
                    p.setValueAt(rs.getString(2), rows, cols++);
                    p.setValueAt(rs.getString(3), rows, cols++);
                    p.setValueAt(rs.getString(4), rows, cols++);
                    p.setValueAt(rs.getString(5), rows, cols++);
                    p.setValueAt(rs.getString(6), rows, cols++);
                    p.setValueAt(rs.getString(7), rows, cols++);
                    p.setValueAt(rs.getString(8), rows, cols++);
                    p.setValueAt(rs.getString(9), rows, cols++);
                    p.setValueAt(rs.getString(10), rows, cols++);
                    p.setValueAt(rs.getInt(11), rows, cols++);
                    p.setValueAt(rs.getString(12), rows, cols++);
                    rows++;
                    cols=0;

                }

                rs.close();
                stmt.close();
                conn.close();

            }

            catch(SQLException e)
            {
                System.out.print("  SQL EXCEPTION  "+e.getMessage());
            }
            catch(Exception ex)
            {
                System.out.print("  EXCEPTION  "+ex.getMessage());
            }
        }
        else   if(team_com.getSelectedIndex()==6)
        {
            int rows=0,cols=0;
            // int i = 0;
            //  DefaultTableModel model=( DefaultTableModel) x.getModel();
            try
            {
                conn=DriverManager.getConnection(db_URL,db_USER,db_password);
                stmt=conn.createStatement();
                rs=stmt.executeQuery("SELECT * FROM sports_mania_table WHERE Team='TYBBMM' AND event='OBSTACLE RACE';");

                while(rs.next())
                {
                    p.setValueAt(rs.getString(1), rows, cols++);
                    p.setValueAt(rs.getString(2), rows, cols++);
                    p.setValueAt(rs.getString(3), rows, cols++);
                    p.setValueAt(rs.getString(4), rows, cols++);
                    p.setValueAt(rs.getString(5), rows, cols++);
                    p.setValueAt(rs.getString(6), rows, cols++);
                    p.setValueAt(rs.getString(7), rows, cols++);
                    p.setValueAt(rs.getString(8), rows, cols++);
                    p.setValueAt(rs.getString(9), rows, cols++);
                    p.setValueAt(rs.getString(10), rows, cols++);
                    p.setValueAt(rs.getInt(11), rows, cols++);
                    p.setValueAt(rs.getString(12), rows, cols++);
                    rows++;
                    cols=0;

                }

                rs.close();
                stmt.close();
                conn.close();

            }

            catch(SQLException e)
            {
                System.out.print("  SQL EXCEPTION  "+e.getMessage());
            }
            catch(Exception ex)
            {
                System.out.print("  EXCEPTION  "+ex.getMessage());
            }
        }
        else   if(team_com.getSelectedIndex()==7)
        {
            int rows=0,cols=0;
            // int i = 0;
            //  DefaultTableModel model=( DefaultTableModel) x.getModel();
            try
            {
                conn=DriverManager.getConnection(db_URL,db_USER,db_password);
                stmt=conn.createStatement();
                rs=stmt.executeQuery("SELECT * FROM sports_mania_table WHERE Team='TYBSW' AND event='OBSTACLE RACE';");

                while(rs.next())
                {
                    p.setValueAt(rs.getString(1), rows, cols++);
                    p.setValueAt(rs.getString(2), rows, cols++);
                    p.setValueAt(rs.getString(3), rows, cols++);
                    p.setValueAt(rs.getString(4), rows, cols++);
                    p.setValueAt(rs.getString(5), rows, cols++);
                    p.setValueAt(rs.getString(6), rows, cols++);
                    p.setValueAt(rs.getString(7), rows, cols++);
                    p.setValueAt(rs.getString(8), rows, cols++);
                    p.setValueAt(rs.getString(9), rows, cols++);
                    p.setValueAt(rs.getString(10), rows, cols++);
                    p.setValueAt(rs.getInt(11), rows, cols++);
                    p.setValueAt(rs.getString(12), rows, cols++);
                    rows++;
                    cols=0;

                }

                rs.close();
                stmt.close();
                conn.close();

            }

            catch(SQLException e)
            {
                System.out.print("  SQL EXCEPTION  "+e.getMessage());
            }
            catch(Exception ex)
            {
                System.out.print("  EXCEPTION  "+ex.getMessage());
            }
        }
        else   if(team_com.getSelectedIndex()==8)
        {
            int rows=0,cols=0;
            // int i = 0;
            //  DefaultTableModel model=( DefaultTableModel) x.getModel();
            try
            {
                conn=DriverManager.getConnection(db_URL,db_USER,db_password);
                stmt=conn.createStatement();
                rs=stmt.executeQuery("SELECT * FROM sports_mania_table WHERE Team='FYBBA T&T' AND event='OBSTACLE RACE';");

                while(rs.next())
                {
                    p.setValueAt(rs.getString(1), rows, cols++);
                    p.setValueAt(rs.getString(2), rows, cols++);
                    p.setValueAt(rs.getString(3), rows, cols++);
                    p.setValueAt(rs.getString(4), rows, cols++);
                    p.setValueAt(rs.getString(5), rows, cols++);
                    p.setValueAt(rs.getString(6), rows, cols++);
                    p.setValueAt(rs.getString(7), rows, cols++);
                    p.setValueAt(rs.getString(8), rows, cols++);
                    p.setValueAt(rs.getString(9), rows, cols++);
                    p.setValueAt(rs.getString(10), rows, cols++);
                    p.setValueAt(rs.getInt(11), rows, cols++);
                    p.setValueAt(rs.getString(12), rows, cols++);
                    rows++;
                    cols=0;

                }

                rs.close();
                stmt.close();
                conn.close();

            }

            catch(SQLException e)
            {
                System.out.print("  SQL EXCEPTION  "+e.getMessage());
            }
            catch(Exception ex)
            {
                System.out.print("  EXCEPTION  "+ex.getMessage());
            }
        }
        else   if(team_com.getSelectedIndex()==9)
        {
            int rows=0,cols=0;
            // int i = 0;
            //  DefaultTableModel model=( DefaultTableModel) x.getModel();
            try
            {
                conn=DriverManager.getConnection(db_URL,db_USER,db_password);
                stmt=conn.createStatement();
                rs=stmt.executeQuery("SELECT * FROM sports_mania_table WHERE Team='SYBBA T&T' AND event='OBSTACLE RACE';");

                while(rs.next())
                {
                    p.setValueAt(rs.getString(1), rows, cols++);
                    p.setValueAt(rs.getString(2), rows, cols++);
                    p.setValueAt(rs.getString(3), rows, cols++);
                    p.setValueAt(rs.getString(4), rows, cols++);
                    p.setValueAt(rs.getString(5), rows, cols++);
                    p.setValueAt(rs.getString(6), rows, cols++);
                    p.setValueAt(rs.getString(7), rows, cols++);
                    p.setValueAt(rs.getString(8), rows, cols++);
                    p.setValueAt(rs.getString(9), rows, cols++);
                    p.setValueAt(rs.getString(10), rows, cols++);
                    p.setValueAt(rs.getInt(11), rows, cols++);
                    p.setValueAt(rs.getString(12), rows, cols++);
                    rows++;
                    cols=0;

                }

                rs.close();
                stmt.close();
                conn.close();

            }

            catch(SQLException e)
            {
                System.out.print("  SQL EXCEPTION  "+e.getMessage());
            }
            catch(Exception ex)
            {
                System.out.print("  EXCEPTION  "+ex.getMessage());
            }
        }
        else   if(team_com.getSelectedIndex()==10)
        {
            int rows=0,cols=0;
            // int i = 0;
            //  DefaultTableModel model=( DefaultTableModel) x.getModel();
            try
            {
                conn=DriverManager.getConnection(db_URL,db_USER,db_password);
                stmt=conn.createStatement();
                rs=stmt.executeQuery("SELECT * FROM sports_mania_table WHERE Team='TYBBA T&T' AND event='OBSTACLE RACE';");

                while(rs.next())
                {
                    p.setValueAt(rs.getString(1), rows, cols++);
                    p.setValueAt(rs.getString(2), rows, cols++);
                    p.setValueAt(rs.getString(3), rows, cols++);
                    p.setValueAt(rs.getString(4), rows, cols++);
                    p.setValueAt(rs.getString(5), rows, cols++);
                    p.setValueAt(rs.getString(6), rows, cols++);
                    p.setValueAt(rs.getString(7), rows, cols++);
                    p.setValueAt(rs.getString(8), rows, cols++);
                    p.setValueAt(rs.getString(9), rows, cols++);
                    p.setValueAt(rs.getString(10), rows, cols++);
                    p.setValueAt(rs.getInt(11), rows, cols++);
                    p.setValueAt(rs.getString(12), rows, cols++);
                    rows++;
                    cols=0;

                }

                rs.close();
                stmt.close();
                conn.close();

            }

            catch(SQLException e)
            {
                System.out.print("  SQL EXCEPTION  "+e.getMessage());
            }
            catch(Exception ex)
            {
                System.out.print("  EXCEPTION  "+ex.getMessage());
            }
        }
        else   if(team_com.getSelectedIndex()==11)
        {
            int rows=0,cols=0;
            // int i = 0;
            //  DefaultTableModel model=( DefaultTableModel) x.getModel();
            try
            {
                conn=DriverManager.getConnection(db_URL,db_USER,db_password);
                stmt=conn.createStatement();
                rs=stmt.executeQuery("SELECT * FROM sports_mania_table WHERE Team='FYBCA' AND event='OBSTACLE RACE';");

                while(rs.next())
                {
                    p.setValueAt(rs.getString(1), rows, cols++);
                    p.setValueAt(rs.getString(2), rows, cols++);
                    p.setValueAt(rs.getString(3), rows, cols++);
                    p.setValueAt(rs.getString(4), rows, cols++);
                    p.setValueAt(rs.getString(5), rows, cols++);
                    p.setValueAt(rs.getString(6), rows, cols++);
                    p.setValueAt(rs.getString(7), rows, cols++);
                    p.setValueAt(rs.getString(8), rows, cols++);
                    p.setValueAt(rs.getString(9), rows, cols++);
                    p.setValueAt(rs.getString(10), rows, cols++);
                    p.setValueAt(rs.getInt(11), rows, cols++);
                    p.setValueAt(rs.getString(12), rows, cols++);
                    rows++;
                    cols=0;

                }

                rs.close();
                stmt.close();
                conn.close();

            }

            catch(SQLException e)
            {
                System.out.print("  SQL EXCEPTION  "+e.getMessage());
            }
            catch(Exception ex)
            {
                System.out.print("  EXCEPTION  "+ex.getMessage());
            }
        }
        else   if(team_com.getSelectedIndex()==12)
        {
            int rows=0,cols=0;
            // int i = 0;
            //  DefaultTableModel model=( DefaultTableModel) x.getModel();
            try
            {
                conn=DriverManager.getConnection(db_URL,db_USER,db_password);
                stmt=conn.createStatement();
                rs=stmt.executeQuery("SELECT * FROM sports_mania_table WHERE Team='SYBCA' AND event='OBSTACLE RACE';");

                while(rs.next())
                {
                    p.setValueAt(rs.getString(1), rows, cols++);
                    p.setValueAt(rs.getString(2), rows, cols++);
                    p.setValueAt(rs.getString(3), rows, cols++);
                    p.setValueAt(rs.getString(4), rows, cols++);
                    p.setValueAt(rs.getString(5), rows, cols++);
                    p.setValueAt(rs.getString(6), rows, cols++);
                    p.setValueAt(rs.getString(7), rows, cols++);
                    p.setValueAt(rs.getString(8), rows, cols++);
                    p.setValueAt(rs.getString(9), rows, cols++);
                    p.setValueAt(rs.getString(10), rows, cols++);
                    p.setValueAt(rs.getInt(11), rows, cols++);
                    p.setValueAt(rs.getString(12), rows, cols++);
                    rows++;
                    cols=0;

                }

                rs.close();
                stmt.close();
                conn.close();

            }

            catch(SQLException e)
            {
                System.out.print("  SQL EXCEPTION  "+e.getMessage());
            }
            catch(Exception ex)
            {
                System.out.print("  EXCEPTION  "+ex.getMessage());
            }
        }
        else   if(team_com.getSelectedIndex()==13)
        {
            int rows=0,cols=0;
            // int i = 0;
            //  DefaultTableModel model=( DefaultTableModel) x.getModel();
            try
            {
                conn=DriverManager.getConnection(db_URL,db_USER,db_password);
                stmt=conn.createStatement();
                rs=stmt.executeQuery("SELECT * FROM sports_mania_table WHERE Team='TYBCA' AND event='OBSTACLE RACE';");

                while(rs.next())
                {
                    p.setValueAt(rs.getString(1), rows, cols++);
                    p.setValueAt(rs.getString(2), rows, cols++);
                    p.setValueAt(rs.getString(3), rows, cols++);
                    p.setValueAt(rs.getString(4), rows, cols++);
                    p.setValueAt(rs.getString(5), rows, cols++);
                    p.setValueAt(rs.getString(6), rows, cols++);
                    p.setValueAt(rs.getString(7), rows, cols++);
                    p.setValueAt(rs.getString(8), rows, cols++);
                    p.setValueAt(rs.getString(9), rows, cols++);
                    p.setValueAt(rs.getString(10), rows, cols++);
                    p.setValueAt(rs.getInt(11), rows, cols++);
                    p.setValueAt(rs.getString(12), rows, cols++);
                    rows++;
                    cols=0;

                }

                rs.close();
                stmt.close();
                conn.close();

            }

            catch(SQLException e)
            {
                System.out.print("  SQL EXCEPTION  "+e.getMessage());
            }
            catch(Exception ex)
            {
                System.out.print("  EXCEPTION  "+ex.getMessage());
            }
        } 
    }//GEN-LAST:event_team_comActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
dispose();  
        games g=new games();
g.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
dispose();  
        Obstacle o=new Obstacle();
        o.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Obstacle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Obstacle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Obstacle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Obstacle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Obstacle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField n_tf;
    private javax.swing.JTable p;
    private javax.swing.JComboBox<String> team_com;
    // End of variables declaration//GEN-END:variables
}
